/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionproductos.view;
import com.mycompany.gestionproductos.model.Producto;
import com.mycompany.gestionproductos.model.ProductoFisico;
import com.mycompany.gestionproductos.model.ProductoDigital;
import javax.swing.JOptionPane;
/**
 *
 * @author kem
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private com.mycompany.gestionproductos.controller.ProductoController controller;

    public VentanaPrincipal(com.mycompany.gestionproductos.controller.ProductoController controller) {
        this.controller = controller;
        initComponents();
    }
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Productos - Corporate Talent Hub");

        jButton1.setText("Registrar Producto");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Listar Productos");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Buscar Productos");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Actualizar Productos");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Eliminar Producto");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Ver Resumen del Inventario");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Salir");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new VentanaRegistrarProducto(controller).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new VentanaListarProductos(controller).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new VentanaBuscarProducto(controller).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigo = JOptionPane.showInputDialog("Ingrese el código del producto a actualizar:");
    if (codigo == null) {
        return; // el usuario canceló el diálogo
    }

    try {
        Producto producto = controller.buscarProducto(codigo);

        String nuevoNombre = JOptionPane.showInputDialog("Nuevo nombre:", producto.getNombre());
        double nuevoPrecio = Double.parseDouble(
                JOptionPane.showInputDialog("Nuevo precio base:", producto.getPrecioBase()));
        int nuevaCantidad = Integer.parseInt(
                JOptionPane.showInputDialog("Nueva cantidad disponible:", producto.getCantidadDisponible()));

        producto.setNombre(nuevoNombre);
        producto.setPrecioBase(nuevoPrecio);
        producto.setCantidadDisponible(nuevaCantidad);

        // Si es físico o digital, también pedimos sus atributos específicos.
        if (producto instanceof ProductoFisico fisico) {
            double nuevoPeso = Double.parseDouble(
                    JOptionPane.showInputDialog("Nuevo peso:", fisico.getPeso()));
            double nuevoCostoEnvio = Double.parseDouble(
                    JOptionPane.showInputDialog("Nuevo costo de envío:", fisico.getCostoEnvio()));
            fisico.setPeso(nuevoPeso);
            fisico.setCostoEnvio(nuevoCostoEnvio);
        } else if (producto instanceof ProductoDigital digital) {
            double nuevoTamanio = Double.parseDouble(
                    JOptionPane.showInputDialog("Nuevo tamaño de archivo:", digital.getTamanioArchivo()));
            String nuevoFormato = JOptionPane.showInputDialog("Nuevo formato:", digital.getFormato());
            digital.setTamanioArchivo(nuevoTamanio);
            digital.setFormato(nuevoFormato);
        }

        controller.actualizarProducto(producto);
        JOptionPane.showMessageDialog(null, "Producto actualizado con éxito");

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String codigo = JOptionPane.showInputDialog("Ingrese el código del producto a eliminar:");
    if (codigo == null) {
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(null,
            "¿Está seguro de eliminar el producto con código " + codigo + "?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            controller.eliminarProducto(codigo);
            JOptionPane.showMessageDialog(null, "Producto eliminado con éxito");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int cantidad = controller.obtenerCantidadProductos();
    double valorTotal = controller.calcularValorTotalInventario();

    String resumen = "========== RESUMEN DEL INVENTARIO ==========\n"
            + "Cantidad de productos registrados: " + cantidad + "\n"
            + "Valor total del inventario: " + valorTotal;

    JOptionPane.showMessageDialog(null, resumen);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
